version: '3.8'
services:
  arma3:
    build: .
    platform: linux/amd64
    container_name: arma3-server
    network_mode: host
    volumes:
      # I've created a folder called shared that I use to contain all of my data
      # Cache the steamcmd. Not required but if you do you will need to download this before
      - './shared/arma3:/arma3'
      # Expose missions / configs / local mods so we can add to them
      #- '/shared/arma3/mpmissions:/arma3/mpmissions'
      #- '/shared/arma3/configs:/arma3/configs'
      #- '/shared/arma3/mods:/arma3/mods'
      # Keep downloaded workshop content
      #- '/shared/arma3/workshop:/arma3/steamapps/workshop/content/107410'
      # Add exported mods list to base arma3 directory
      #- '/shared/arma3/mods.html:/arma3/mods.html'

    environment:
      - WORKSHOP_MODS=mods.html
      - ARMA_CDLC=
      - STEAM_BRANCH=public
      - STEAM_USERNAME=
      - STEAM_PASSWORD=
      - DEBUG=1
    restart: unless-stopped
  
